#!/bin/sh

mkdir -p src/components src/styles src/__tests__ src/hooks

touch src/components/$1.js
touch src/styles/$1.css
touch src/__tests__/$1.test.js

sed -e "s/COMPONENT_NAME/$1/g" ~/Desktop/create-react-component/code_templates/component.js > src/components/$1.js
sed -e "s/COMPONENT_NAME/$1/g" ~/Desktop/create-react-component/code_templates/component.css > src/styles/$1.css
